name: constantinesphotos
favicon: null
layout_spectrum: 0.14625
typography_spectrum: 0.39505
title: Constantine's Photos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e6e8'
    - '#050507'
    - '#6c4639'
    - '#b08f8a'
    - '#c61f21'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
