typography_spectrum: 0.39505
color:
  brandColors:
    - '#cfcfcf'
    - '#000000'
    - '#6c6761'
    - '#00a4d1'
    - '#00717b'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.14625
analytics:
  google: UA-82908034-1
  facebook: null
  twitter: null
name: constantinesphotos
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Constantine's Photos
description: Freelance Professional Creating Photographic Masterpieces Daily
purpose: []
